const DataPenerbangan = [
    [
        "Bandung",
        "Lampung",
        "Jawa",
        "Ambon",
        "Aceh",
        "Jakarta",
        "Jambi",
        "Maluku",
        "Pontianak",
        "Samarinda",
    ],
    [
        "Lampung",
        "Bandung",
        "Ambon",
        "Jawa",
        "Samarinda",
        "Maluku",
        "Pontianak",
        "Jakarta",
        "Jambi",
        "Aceh",
    ],
    [
        "01 Januari 2022",
        "01 Januari 2022",
        "01 Januari 2022",
        "01 Januari 2022",
        "01 Januari 2022",
        "01 Januari 2022",
    ],
    [
        "Elang",
        "Lion Air",
        "Majapahit",
        "Elang",
        "Lion Air",
        "Majapahit",
        "Majapahit",
        "Elang",
        "Lion Air",
        "Majapahit",
    ],
];

export default DataPenerbangan;